// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
@file:JvmName("-BluePrintProcessingServiceRpcOverloads")

package org.onap.ccsdk.cds.controllerblueprints.processing.api

import com.github.marcoferrer.krotoplus.coroutines.client.ClientBidiCallChannel
import com.github.marcoferrer.krotoplus.coroutines.client.clientCallBidiStreaming
import kotlin.jvm.JvmName
import org.onap.ccsdk.cds.controllerblueprints.processing.api.BluePrintProcessingServiceGrpc.BluePrintProcessingServiceStub

fun BluePrintProcessingServiceStub.process(): ClientBidiCallChannel<ExecutionServiceInput,
        ExecutionServiceOutput> =
        clientCallBidiStreaming(BluePrintProcessingServiceGrpc.getProcessMethod())
