# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.BluePrintManagement_pb2 as BluePrintManagement__pb2


class BluePrintManagementServiceStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.downloadBlueprint = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/downloadBlueprint',
        request_serializer=BluePrintManagement__pb2.BluePrintDownloadInput.SerializeToString,
        response_deserializer=BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
    )
    self.uploadBlueprint = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/uploadBlueprint',
        request_serializer=BluePrintManagement__pb2.BluePrintUploadInput.SerializeToString,
        response_deserializer=BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
    )
    self.removeBlueprint = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/removeBlueprint',
        request_serializer=BluePrintManagement__pb2.BluePrintRemoveInput.SerializeToString,
        response_deserializer=BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
    )
    self.bootstrapBlueprint = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/bootstrapBlueprint',
        request_serializer=BluePrintManagement__pb2.BluePrintBootstrapInput.SerializeToString,
        response_deserializer=BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
    )


class BluePrintManagementServiceServicer(object):
  """Missing associated documentation comment in .proto file."""

  def downloadBlueprint(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def uploadBlueprint(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeBlueprint(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def bootstrapBlueprint(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BluePrintManagementServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
    'downloadBlueprint': grpc.unary_unary_rpc_method_handler(
        servicer.downloadBlueprint,
        request_deserializer=BluePrintManagement__pb2.BluePrintDownloadInput.FromString,
        response_serializer=BluePrintManagement__pb2.BluePrintManagementOutput.SerializeToString,
    ),
    'uploadBlueprint': grpc.unary_unary_rpc_method_handler(
        servicer.uploadBlueprint,
        request_deserializer=BluePrintManagement__pb2.BluePrintUploadInput.FromString,
        response_serializer=BluePrintManagement__pb2.BluePrintManagementOutput.SerializeToString,
    ),
    'removeBlueprint': grpc.unary_unary_rpc_method_handler(
        servicer.removeBlueprint,
        request_deserializer=BluePrintManagement__pb2.BluePrintRemoveInput.FromString,
        response_serializer=BluePrintManagement__pb2.BluePrintManagementOutput.SerializeToString,
    ),
    'bootstrapBlueprint': grpc.unary_unary_rpc_method_handler(
        servicer.bootstrapBlueprint,
        request_deserializer=BluePrintManagement__pb2.BluePrintBootstrapInput.FromString,
        response_serializer=BluePrintManagement__pb2.BluePrintManagementOutput.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BluePrintManagementService(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def downloadBlueprint(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/downloadBlueprint',
                                         BluePrintManagement__pb2.BluePrintDownloadInput.SerializeToString,
                                         BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def uploadBlueprint(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/uploadBlueprint',
                                         BluePrintManagement__pb2.BluePrintUploadInput.SerializeToString,
                                         BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def removeBlueprint(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/removeBlueprint',
                                         BluePrintManagement__pb2.BluePrintRemoveInput.SerializeToString,
                                         BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def bootstrapBlueprint(request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/org.onap.ccsdk.cds.controllerblueprints.management.api.BluePrintManagementService/bootstrapBlueprint',
                                         BluePrintManagement__pb2.BluePrintBootstrapInput.SerializeToString,
                                         BluePrintManagement__pb2.BluePrintManagementOutput.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
