[tox]
envlist=py39
skipsdist=True
[testenv]
setenv =
    CONFIGURATION = {toxinidir}/../configuration-local.ini
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
    {toxinidir}/../../py-modules/common
    -r{toxinidir}/../artifact-manager/requirements.txt
    {toxinidir}/../artifact-manager
commands = pytest resource_resolution/
[testenv:codelint]
deps =
    black
commands = black -l 120 --check {posargs:.}
[testenv:doclint]
deps =
    flake8-docstrings
commands = flake8 --doctest --docstring-convention google --max-line-length 120 --exclude .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,*test.py --select=D {posargs:.}
[testenv:coverage]
basepython = python3.9
setenv =
    CONFIGURATION = {toxinidir}/../configuration-local.ini
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
    {toxinidir}/../../py-modules/common
    -r{toxinidir}/../artifact-manager/requirements.txt
    {toxinidir}/../artifact-manager
    pytest-cov
commands = pytest --cov=manager --cov=resource_resolution --cov-fail-under=60 --cov-config={toxinidir}/.coveragerc resource_resolution/
