SERVICE_LOG = "log"
SERVICE_NETCONF = "netconfService"
SERVICE_MESSAGE = "messageService"

PARAM_REQUEST_ID = "requestId"
PARAM_ACTION = "action"

STATUS_SUCCESS = "success"
STATUS_FAILURE = "failure"

CONFIG_TARGET_RUNNING = "running"
CONFIG_TARGET_CANDIDATE = "candidate"
CONFIG_DEFAULT_OPERATION_MERGE = "merge"
CONFIG_DEFAULT_OPERATION_REPLACE = "replace"
CONFIG_DEFAULT_OPERATION_NONE = "none"
