# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.CommandExecutor_pb2 as CommandExecutor__pb2


class CommandExecutorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.uploadBlueprint = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.command.api.CommandExecutorService/uploadBlueprint',
        request_serializer=CommandExecutor__pb2.UploadBlueprintInput.SerializeToString,
        response_deserializer=CommandExecutor__pb2.UploadBlueprintOutput.FromString,
        )
    self.prepareEnv = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.command.api.CommandExecutorService/prepareEnv',
        request_serializer=CommandExecutor__pb2.PrepareEnvInput.SerializeToString,
        response_deserializer=CommandExecutor__pb2.ExecutionOutput.FromString,
        )
    self.executeCommand = channel.unary_unary(
        '/org.onap.ccsdk.cds.controllerblueprints.command.api.CommandExecutorService/executeCommand',
        request_serializer=CommandExecutor__pb2.ExecutionInput.SerializeToString,
        response_deserializer=CommandExecutor__pb2.ExecutionOutput.FromString,
        )


class CommandExecutorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def uploadBlueprint(self, request, context):
    """rpc to upload the CBA
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def prepareEnv(self, request, context):
    """prepare Python environment
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def executeCommand(self, request, context):
    """execute the actual command.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommandExecutorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'uploadBlueprint': grpc.unary_unary_rpc_method_handler(
          servicer.uploadBlueprint,
          request_deserializer=CommandExecutor__pb2.UploadBlueprintInput.FromString,
          response_serializer=CommandExecutor__pb2.UploadBlueprintOutput.SerializeToString,
      ),
      'prepareEnv': grpc.unary_unary_rpc_method_handler(
          servicer.prepareEnv,
          request_deserializer=CommandExecutor__pb2.PrepareEnvInput.FromString,
          response_serializer=CommandExecutor__pb2.ExecutionOutput.SerializeToString,
      ),
      'executeCommand': grpc.unary_unary_rpc_method_handler(
          servicer.executeCommand,
          request_deserializer=CommandExecutor__pb2.ExecutionInput.FromString,
          response_serializer=CommandExecutor__pb2.ExecutionOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.onap.ccsdk.cds.controllerblueprints.command.api.CommandExecutorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
